name: workflow runner

on:
  workflow_dispatch: 

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: show OS
        run: |
          echo "this job is running on ubuntu runner"
          echo "this is running on OS: $RUNNER_OS"
          
      
  


